import type { AppState, DocumentRecord, FutureModule, HaccpSection, KnowledgeSource } from "./domain";

const now = "2026-06-23T10:00:00.000Z";

const documents: DocumentRecord[] = [
  {
    id: "doc-001",
    clientId: "client-001",
    projectId: "project-001",
    documentType: "business_license",
    fileName: "angkor-cashew-business-license.pdf",
    storageProvider: "local_placeholder",
    storageId: "local/doc-001",
    status: "accepted",
    uploadedAt: now,
  },
  {
    id: "doc-002",
    clientId: "client-001",
    projectId: "project-001",
    documentType: "factory_layout",
    fileName: "factory-layout-v1.pdf",
    storageProvider: "local_placeholder",
    storageId: "local/doc-002",
    status: "review_needed",
    uploadedAt: now,
  },
  {
    id: "doc-003",
    clientId: "client-001",
    projectId: "project-001",
    documentType: "process_flow",
    fileName: "roasted-cashew-process-flow.xlsx",
    storageProvider: "local_placeholder",
    storageId: "local/doc-003",
    status: "accepted",
    uploadedAt: now,
  },
  {
    id: "doc-004",
    clientId: "client-002",
    projectId: "project-002",
    documentType: "business_license",
    fileName: "mekong-nuts-license.pdf",
    storageProvider: "local_placeholder",
    storageId: "local/doc-004",
    status: "accepted",
    uploadedAt: now,
  },
  {
    id: "doc-005",
    clientId: "client-003",
    projectId: "project-003",
    documentType: "business_license",
    fileName: "golden-cashew-business-license.pdf",
    storageProvider: "local_placeholder",
    storageId: "local/doc-005",
    status: "accepted",
    uploadedAt: now,
  },
  {
    id: "doc-006",
    clientId: "client-003",
    projectId: "project-003",
    documentType: "food_production_license",
    fileName: "golden-cashew-production-license.pdf",
    storageProvider: "local_placeholder",
    storageId: "local/doc-006",
    status: "accepted",
    uploadedAt: now,
  },
  {
    id: "doc-007",
    clientId: "client-003",
    projectId: "project-003",
    documentType: "factory_layout",
    fileName: "golden-cashew-factory-layout.pdf",
    storageProvider: "local_placeholder",
    storageId: "local/doc-007",
    status: "accepted",
    uploadedAt: now,
  },
  {
    id: "doc-008",
    clientId: "client-003",
    projectId: "project-003",
    documentType: "process_flow",
    fileName: "golden-cashew-demo-process-flow.txt",
    storageProvider: "local_placeholder",
    storageId: "local/doc-008",
    status: "review_needed",
    uploadedAt: now,
  },
];

const haccpSectionTypes: HaccpSection["sectionType"][] = [
  "PRODUCT_PROCESS",
  "HAZARD_ANALYSIS",
  "CCP_PLAN",
  "SSOP",
  "GMP_PRP",
  "MANUAL_SUMMARY",
];

const haccpSections: HaccpSection[] = [
  ...haccpSectionTypes.map((sectionType, index) => ({
    id: `section-001-${index + 1}`,
    clientId: "client-001",
    projectId: "project-001",
    sectionType,
    status: index === 0 ? "generated" as const : "not_started" as const,
    inputJson: {},
    outputJson:
      index === 0
        ? {
            product_description: "Roasted cashew kernels packed in sealed food-grade bags for export.",
            process_steps: ["Raw nut receiving", "Shelling", "Drying", "Roasting", "Cooling", "Metal detection", "Packing"],
          }
        : null,
    reviewerNotes: "",
    generatedAt: index === 0 ? now : null,
    reviewedAt: null,
  })),
  ...haccpSectionTypes.map((sectionType, index) => ({
    id: `section-003-${index + 1}`,
    clientId: "client-003",
    projectId: "project-003",
    sectionType,
    status: "not_started" as const,
    inputJson: {
      process_flow: [
        "Raw Cashew Reception",
        "Cleaning",
        "Drying",
        "Shelling",
        "Kernel Separation",
        "Roasting",
        "Cooling",
        "Metal Detection",
        "Packing",
        "Storage",
        "Export",
      ],
    },
    outputJson: null,
    reviewerNotes: "Demo Factory Data Pack V1 placeholder.",
    generatedAt: null,
    reviewedAt: null,
  })),
];

const knowledgeSources: KnowledgeSource[] = [
  {
    id: "kb-haccp-001",
    title: "HACCP implementation baseline",
    category: "HACCP",
    marketGroup: "All",
    productCategory: "All",
    sourceType: "checklist",
    summary: "HACCP packages should connect product description, process flow, hazard analysis, CCP plan, SSOP, GMP/PRP, verification, and records.",
    tags: ["haccp", "hazard", "ccp", "ssop", "gmp", "records", "audit"],
    updatedAt: now,
  },
  {
    id: "kb-gacc-001",
    title: "China GACC registration route",
    category: "GACC",
    marketGroup: "China",
    productCategory: "Cashew",
    sourceType: "internal_note",
    summary: "China-bound cashew projects should prepare company profile, product description, authority recommendation materials, HACCP evidence, and CIFER registration data.",
    tags: ["gacc", "china", "cifer", "registration", "cashew", "documents"],
    updatedAt: now,
  },
  {
    id: "kb-market-001",
    title: "US/EU importer audit readiness",
    category: "Market",
    marketGroup: "US_EU",
    productCategory: "All",
    sourceType: "checklist",
    summary: "US/EU export readiness should emphasize traceability, allergen control, supplier approval, recall procedure, lab evidence, and buyer audit records.",
    tags: ["readiness", "documents", "audit", "traceability", "allergen", "supplier"],
    updatedAt: now,
  },
  {
    id: "kb-label-001",
    title: "China label compliance placeholder",
    category: "Labeling",
    marketGroup: "China",
    productCategory: "All",
    sourceType: "regulation_reference",
    summary: "China label work should be handled as a later rule-first module. Required fields and nutrition format should be code-checked before AI drafts wording suggestions.",
    tags: ["china", "label", "gb7718", "gb28050", "readiness"],
    updatedAt: now,
  },
  {
    id: "kb-training-001",
    title: "Khmer worker training baseline",
    category: "Training",
    marketGroup: "All",
    productCategory: "All",
    sourceType: "template",
    summary: "Worker training should cover handwashing, hygiene, sanitation, pest reporting, CCP monitoring, correction reporting, attendance, quiz evidence, and Khmer-language delivery.",
    tags: ["training", "khmer", "worker", "quiz", "records", "haccp"],
    updatedAt: now,
  },
];

const futureModules: FutureModule[] = [
  {
    id: "future-free-snapshot",
    title: "Free Readiness Snapshot",
    phase: "Phase 1",
    status: "designing",
    description: "Rules-only intake, target market selection, basic 0-100 score, top gaps, and lead capture without AI cost.",
  },
  {
    id: "future-client-portal",
    title: "Client portal",
    phase: "Phase 3",
    status: "planned",
    description: "Factory owners and quality managers can log in to view progress, missing files, tasks, and timelines.",
  },
  {
    id: "future-research-agent",
    title: "Research Agent",
    phase: "Phase 2",
    status: "planned",
    description: "Maintain market rule notes, certification references, and source summaries for consultant review.",
  },
  {
    id: "future-sales-crm-agent",
    title: "Sales / CRM Agent",
    phase: "Phase 2",
    status: "planned",
    description: "Convert readiness scores into service recommendations, meeting follow-up, quotation stage, and annual support pipeline.",
  },
  {
    id: "future-payments",
    title: "Payments",
    phase: "Commercial phase",
    status: "planned",
    description: "Subscription, service fees, certification upgrade fees, training fees, and label review fees.",
  },
  {
    id: "future-google-drive",
    title: "Google Drive OAuth automation",
    phase: "Phase 1.5",
    status: "planned",
    description: "Create client folders, upload documents, store file IDs, and keep project files organized by stage.",
  },
  {
    id: "future-label-checker",
    title: "GB7718 / GB28050 label checker",
    phase: "Phase 4",
    status: "planned",
    description: "Rule-first China label checks with AI-generated correction suggestions and Chinese label drafts.",
  },
  {
    id: "future-lab-evidence",
    title: "Lab report evidence tracking",
    phase: "Phase 4",
    status: "planned",
    description: "Track third-party test reports, expiry dates, missing evidence, and renewal reminders without performing laboratory testing.",
  },
  {
    id: "future-capa",
    title: "CAPA workflow",
    phase: "Phase 5",
    status: "planned",
    description: "Non-conformity, corrective action, verification, closure evidence, and audit-ready follow-up.",
  },
  {
    id: "future-khmer-language",
    title: "Khmer language layer",
    phase: "Phase 6",
    status: "planned",
    description: "Khmer-ready worker training, factory tasks, and client-facing guidance while English remains the export document baseline.",
  },
  {
    id: "future-traceability",
    title: "Batch traceability / QR code",
    phase: "Phase 8",
    status: "planned",
    description: "Supplier lots, raw material lots, production batches, packaging batches, shipments, and recall simulation.",
  },
  {
    id: "future-multi-industry",
    title: "Multi-industry rule packs",
    phase: "Phase 9",
    status: "planned",
    description: "Extend modular rules from cashew to pepper, mango, rice, dried fruit, seafood, and processed food.",
  },
];

export const initialState: AppState = {
  clients: [
    {
      id: "client-001",
      name: "Angkor Premium Cashew",
      country: "Cambodia",
      factoryLocation: "Kampong Thom",
      contactName: "Sok Dara",
      contactEmail: "dara@example.com",
      productType: "roasted cashew kernels",
      targetMarket: "China",
      employeeCount: 62,
    },
    {
      id: "client-002",
      name: "Mekong Nuts Processing",
      country: "Cambodia",
      factoryLocation: "Phnom Penh",
      contactName: "Chan Theary",
      contactEmail: "theary@example.com",
      productType: "raw cashew kernels",
      targetMarket: "EU",
      employeeCount: 38,
    },
    {
      id: "client-003",
      name: "Cambodia Golden Cashew Co., Ltd.",
      country: "Cambodia",
      factoryLocation: "Kampong Thom Province",
      contactName: "Demo Quality Manager",
      contactEmail: "qa@goldencashew.example",
      productType: "roasted cashew kernels",
      targetMarket: "China",
      employeeCount: 120,
    },
  ],
  projects: [
    {
      id: "project-001",
      clientId: "client-001",
      certificationType: "HACCP",
      productCategory: "Cashew",
      haccpStatus: "OPERATION_RUNNING",
      gaccStatus: "DOCUMENT_COLLECTION",
      haccpStartDate: "2026-05-05",
      haccpOperationStartDate: "2026-05-20",
      expectedCertificationDate: "2026-09-01",
    },
    {
      id: "project-002",
      clientId: "client-002",
      certificationType: "HACCP",
      productCategory: "Cashew",
      haccpStatus: "GAP_ANALYSIS",
      gaccStatus: "ELIGIBILITY_CHECK",
      haccpStartDate: "2026-06-10",
      haccpOperationStartDate: null,
      expectedCertificationDate: null,
    },
    {
      id: "project-003",
      clientId: "client-003",
      certificationType: "HACCP",
      productCategory: "Cashew",
      haccpStatus: "GAP_ANALYSIS",
      gaccStatus: "ELIGIBILITY_CHECK",
      haccpStartDate: "2026-06-24",
      haccpOperationStartDate: null,
      expectedCertificationDate: null,
    },
  ],
  documents,
  aiGenerations: [],
  auditLogs: [
    {
      id: "audit-001",
      clientId: "client-001",
      projectId: "project-001",
      action: "project_created",
      details: "Initial HACCP and GACC tracks created.",
      createdAt: now,
    },
    {
      id: "audit-002",
      clientId: "client-003",
      projectId: "project-003",
      action: "demo_data_loaded",
      details: "Demo Factory Data Pack V1 loaded: China target market, roasted cashew kernels, 120 employees, 300 tons/year.",
      createdAt: now,
    },
    {
      id: "audit-003",
      clientId: "client-003",
      projectId: "project-003",
      action: "issues_identified",
      details: "Missing roast temperature logs, metal detection records, worker training records, traceability details, updated water test, pest control plan, internal audit record, and GACC package.",
      createdAt: now,
    },
  ],
  haccpSections,
  readinessScores: [],
  knowledgeSources,
  futureModules,
};
